### ISSUE TITLE
Process 'command 'C:\Program Files\Java\jdk1.7.0_40\bin\java.exe'' finished with non-zero exit value 1

### ISSUE THREAD

**Issue by guozhiling** [bunnyblue/DroidFix#5]
在进行debugDroidFix运行的时候出现的错误,错误信息
Exception in thread "main" java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.LinkedList.checkElementIndex(LinkedList.java:553)
	at java.util.LinkedList.get(LinkedList.java:474)
	at io.github.bunnyblue.droidfix.classcomputer.gradleImpl.GradleImpl15.extract(GradleImpl15.java:49)
	at io.github.bunnyblue.droidfix.classcomputer.proguard.MappingMapper.processRawClassesJarFormat(MappingMapper.java:85)
	at io.github.bunnyblue.droidfix.classcomputer.proguard.MappingMapper.processRawClasses(MappingMapper.java:76)
	at io.github.bunnyblue.droidfix.classcomputer.classes.ClassInject.injectConstructionClasses(ClassInject.java:60)
	at io.github.bunnyblue.droidfix.classcomputer.ClassComputer.injectClasses(ClassComputer.java:127)
	at io.github.bunnyblue.droidfix.classcomputer.ClassComputer.main(ClassComputer.java:101)
:app:proguardDebugHotFix FAILED

**Comment by bunnyblue** [comment]
app/build/intermediates/transforms/proguard下面有main.jar吗？你debug开混淆了没？没开混淆的话没用应该

**Comment by guozhiling** [comment]
现在是没开混淆的。
app/build/intermediates/transforms/proguard没有main.jar

**Comment by guozhiling** [comment]
刚才又重新编译了下，没开混淆，就没出现那个错误了

**Comment by bunnyblue** [comment]
这个只做了处理混淆的，没开混淆处理的可能会报错，目录不太一样
